# only needed before ubuntu noble, replaced by time-daemon after
- name: pkg
  apt:
    name: ntp
  # only needed before ubuntu noble, replaced by time-daemon after
  when:
    - ansible_facts['os_family'] == "Debian"
    - ansible_facts['distribution'] == "Ubuntu"
    - ansible_facts['distribution_version'] == "22.04"
