- name: packages
  package:
    name: "{{ ansible_facts['common_tools'] }}"

- name: "packages {{ ansible_facts['architecture'] }}"
  package:
    name: "{{ ansible_facts.get('common_tools_' + ansible_facts['architecture'], []) }}"
