- name: config default branch
  become: true
  become_user: "{{ item.user }}"
  shell: >
    rustup default stable
  with_items: "{{ users.values() | list }}"

- name: config update
  become: true
  become_user: "{{ item.user }}"
  shell: >
    rustup update
  with_items: "{{ users.values() | list }}"
