- name: config udev
  become: true
  template:
    src: etc/udev/rules.d/70-u2f.rules.j2
    dest: /etc/udev/rules.d/70-u2f.rules
    owner: root
    group: root
    mode: '0644'
  notify:
    - reload udev
    - trigger udev
