- name: repo ppa-yubico pins
  template:
    src: etc/apt/preferences.d/ppa-yubico.pref.j2
    dest: /etc/apt/preferences.d/ppa-yubico.pref
  when: ansible_distribution == "Ubuntu"

- name: repo
  template:
    src: etc/apt/sources.list.d/ppa-yubico.list.j2
    dest: /etc/apt/sources.list.d/ppa-yubico.list
  notify:
    - apt-get update
  when: ansible_distribution == "Ubuntu"

- name: repo dir keyrings
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  when: ansible_distribution == "Ubuntu"

- name: repo remove legacy key
  file:
    path: /etc/apt/trusted.gpg.d/ppa-yubico.gpg
    state: absent
  when: ansible_distribution == "Ubuntu"

- name: repo key
  get_url:
    url: "https://keyserver.ubuntu.com/pks/lookup?op=get&options=mr&search=0x3653E21064B19D134466702E43D5C49532CBA1A9"
    dest: /etc/apt/keyrings/ppa-yubico.asc
    mode: '0644'
  notify:
    - apt-get update
  when: ansible_distribution == "Ubuntu"

- meta: flush_handlers
  when: ansible_distribution == "Ubuntu"
