- name: repo remove ppa-yubico
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/apt/preferences.d/ppa-yubico.pref
    - /etc/apt/sources.list.d/ppa-yubico.list
    - /etc/apt/keyrings/ppa-yubico.asc
    - /etc/apt/trusted.gpg.d/ppa-yubico.gpg
  notify:
    - apt-get update
  when: ansible_distribution == "Ubuntu"

- meta: flush_handlers
  when: ansible_distribution == "Ubuntu"
