---
default_install_hook_types: [pre-commit, pre-push]

repos:
  - repo: local
    hooks:
      - id: yamllint
        name: yamllint
        entry: yamllint -s
        language: system
        types: [yaml]

      - id: cargo-fmt
        name: cargo fmt --check
        entry: cargo fmt --manifest-path Cargo.toml --all -- --check
        language: system
        files: ^.*\.rs$
        pass_filenames: false

      - id: cargo-clippy
        name: cargo clippy
        entry: cargo clippy --manifest-path Cargo.toml --all-targets --locked -- -D warnings
        language: system
        files: ^(.*\.rs|Cargo\.(toml|lock))$
        pass_filenames: false

      - id: act-rust-workflow
        name: act .github/workflows/rust.yml (pre-push)
        entry: act -W .github/workflows/rust.yml pull_request
        language: system
        stages: [pre-push]
        files: ^(.*\.rs|Cargo\.(toml|lock)|\.github/workflows/rust\.yml$)
        pass_filenames: false
