---
extends: default

rules:
  line-length:
    max: 160
    level: warning
  truthy:
    allowed-values: ['true', 'false']
    check-keys: false
  comments:
    require-starting-space: true
    ignore-shebangs: true
    min-spaces-from-content: 1
  document-start: disable
  braces:
    max-spaces-inside: 1
  octal-values:
    forbid-implicit-octal: true
    forbid-explicit-octal: false

ignore:
  - .git/
