version: '2'

services:
  base-ubuntu:
    extends:
      file: docker-compose-default.yml
      service: default
    image: prius/base-ubuntu
    build:
      dockerfile: /home/prius/git/github.com/prius/ansible-playbooks/docker-base-ubuntu.Dockerfile

  chromium-browser:
    extends:
      file: docker-compose-default.yml
      service: default
    image: prius/chromium-browser
    build:
      dockerfile: /home/prius/git/github.com/prius/ansible-playbooks/docker-chromium-browser.Dockerfile
    volumes:
      - "/home/prius/.config/chromium/:/home/prius/.config/chromium/"
      - "/tmp/.X11-unix/:/tmp/.X11-unix/"
      - "/sys/fs/cgroup:/sys/fs/cgroup"
      - "/run/dbus/:/run/dbus/"
    devices:
      - "/dev/snd:/dev/snd"
      - "/dev/shm:/dev/shm"
    environment:
      - container=docker
      - DISPLAY=${DISPLAY}
    privileged: true
    cap_add:
      - SYS_ADMIN
      - SYS_PTRACE
