version: '2'

services:
  default:
    network_mode: bridge
    build:
      context: /home/prius/git/github.com/prius/ansible-playbooks
    entrypoint: sleep infinity
    tmpfs:
      - /tmp:mode=1777
      - /var/tmp:mode=1777
      - /home/prius/.cache:uid=1000,gid=1000
    security_opt:
      - seccomp:unconfined
    volumes:
      - "/home/prius/git/github.com/prius/ansible-playbooks:/etc/my/ansible"
      - "/home/prius/.bashrc:/home/prius/.bashrc"
      - "/home/prius/.vim:/home/prius/.vim"
      - "/home/prius/.vimrc:/home/prius/.vimrc"
