- name: config rc files
  synchronize:
    src: home/
    dest: "{{ item.home }}"
    rsync_opts:
      - "--exclude=.git"
      - "--exclude=.gitmodules"
      - "--exclude=.gitconfig"
      - "--exclude=.gitignore"
      - "--chown={{ item.user }}:{{ item.user }}"
      - "--update" # skip files that are newer on the receiver
      - "--times" # preserve modification times
  with_items: "{{ users.values() | list }}"

- name: config user-dir
  file:
    path: "{{ item.home }}"
    state: directory
    owner: "{{ item.user }}"
    mode: '0700'
  with_items: "{{ users.values() | list }}"

- name: config ssh-dir
  file:
    path: "{{ item.home }}/.ssh/"
    state: directory
    owner: "{{ item.user }}"
    mode: '0700'
  with_items: "{{ users.values() | list }}"

- name: config local-bin-dir
  file:
    path: "{{ item.home }}/.local/bin/"
    state: directory
    recurse: true
    owner: "{{ item.user }}"
    mode: '0777'
  with_items: "{{ users.values() | list }}"

- name: config fonts-dir
  file:
    path: "{{ item.home }}/.local/share/fonts/fonts/"
    state: directory
    recurse: true
    owner: "{{ item.user }}"
    mode: '0777'
  with_items: "{{ users.values() | list }}"

- name: config venv-dir
  file:
    path: "{{ item.home }}/venv/"
    state: directory
    owner: "{{ item.user }}"
    mode: '0777'
  with_items: "{{ users.values() | list }}"

- name: config .private dir
  file:
    path: "{{ item.home }}/.private/"
    state: directory
    owner: "{{ item.user }}"
    mode: '0700'
  with_items: "{{ users.values() | list }}"

- name: config .config dir
  file:
    path: "{{ item.home }}/.config/"
    state: directory
    owner: "{{ item.user }}"
    mode: '0755'
  with_items: "{{ users.values() | list }}"

- name: config .config/autostart dir
  file:
    path: "{{ item.home }}/.config/autostart/"
    state: directory
    owner: "{{ item.user }}"
    mode: '0755'
  with_items: "{{ users.values() | list }}"

- name: config .config/systemd dir
  file:
    path: "{{ item.home }}/.config/systemd/"
    state: directory
    owner: "{{ item.user }}"
    mode: '0755'
  with_items: "{{ users.values() | list }}"

- name: config .config/systemd/user dir
  file:
    path: "{{ item.home }}/.config/systemd/user/"
    state: directory
    owner: "{{ item.user }}"
    mode: '0755'
  with_items: "{{ users.values() | list }}"

- name: config .cache mount
  copy:
    content: |
      [Unit]
      Description=Mount tmpfs to /home/{{ item.user }}/.cache

      [Mount]
      Where=/home/{{ item.user }}/.cache
      Options=defaults,noatime,nodiratime,nosuid,nodev,mode=1777
      What=tmpfs
      Type=tmpfs

      [Install]
      WantedBy=multi-user.target
    dest: "/etc/systemd/system/home-{{ item.user }}-.cache.mount"
    owner: "root"
  with_items: "{{ users.values() | list }}"
  when: item.user != 'root' and ansible_virtualization_type != 'docker' and ansible_user_id == 'root'

- name: config .cache mount enable systemd
  systemd:
    name: "home-{{ item.user }}-.cache.mount"
    state: started
    enabled: yes
    daemon_reload: yes
  with_items: "{{ users.values() | list }}"
  when: item.user != 'root' and ansible_virtualization_type != 'docker' and ansible_user_id == 'root'

- name: config .private dir for user
  file:
    name: "{{ item.home }}/.private"
    owner: "{{ item.user }}"
    mode: '0700'
    state: directory
  when: "'custom_secrets' in item"
  with_items: "{{ users.values() | list }}"

- name: config custom secret
  template:
    src: custom_secret.j2
    dest: "{{ item.0.home }}/.private/{{ item.1.filename }}"
    owner: "{{ item.0.user }}"
    mode: '0600'
  with_subelements:
    - "{{ users.values() | list }}"
    - custom_secrets
    - skip_missing: True

- name: config custom secret from file
  copy:
    src: "{{ item.1.src_dir }}/{{ item.1.filename }}"
    dest: "{{ item.0.home }}/.private/{{ item.1.filename }}"
    owner: "{{ item.0.user }}"
    mode: '0600'
  with_subelements:
    - "{{ users.values() | list }}"
    - custom_secrets_from_file
    - skip_missing: True
