---
- name: package ubuntu-desktop
  apt:
    name: ubuntu-desktop
    install_recommends: false

- name: packages remove unnecessary
  apt:
    name: "{{ item }}"
    state: absent
  with_items:
    - apport
    - apport-gtk
    - apport-symptoms
    - avahi-autoipd
    - avahi-daemon
    - avahi-utils
    - dnsmasq
    - gnome-software
    - gnome-software-common
    - kerneloops
