---
- name: config allow-unauthenticated
  template:
    src: etc/apt/apt.conf.d/30allowunauth.j2
    dest: /etc/apt/apt.conf.d/30allowunauth

- name: config default-release
  template:
    src: etc/apt/apt.conf.d/00release.j2
    dest: /etc/apt/apt.conf.d/00release

- name: config timeout
  template:
    src: etc/apt/apt.conf.d/00timeout.j2
    dest: /etc/apt/apt.conf.d/00timeout

- name: config no install recommends
  template:
    src: etc/apt/apt.conf.d/00noinstallrecommends.j2
    dest: /etc/apt/apt.conf.d/00noinstallrecommends

- name: config debug
  template:
    src: etc/apt/apt.conf.d/99debug.j2
    dest: /etc/apt/apt.conf.d/99debug

- name: config disable-periodic actions
  template:
    src: etc/apt/apt.conf.d/10periodic.j2
    dest: /etc/apt/apt.conf.d/10periodic

- name: config disable-motd-update-on-login
  file:
    path: /etc/update-motd.d/90-updates-available
    state: absent

- name: config disable-update-notifier
  file:
    path: /etc/apt/apt.conf.d/99update-notifier
    state: absent

- name: config disable-update-notifier-cron-daily
  file:
    path: /etc/cron.daily/update-notifier-common
    state: absent

- name: config disable-update-notifier-cron-weekly
  file:
    path: /etc/cron.weekly/update-notifier-common
    state: absent
