# For better support of PPA repos
- name: package software-properties-common
  apt:
    name: software-properties-common

- name: package python-pycurl
  apt:
    name: python-pycurl
  # FIXME: missing since Ubuntu jammy
  ignore_errors: yes

- name: package python3-pycurl
  apt:
    name: python3-pycurl

- name: package python-apt
  apt:
    name: python-apt
  # FIXME: missing since Ubuntu jammy
  ignore_errors: yes

- name: package python3-apt
  apt:
    name: python3-apt

# For handling https repositories
- name: package apt-transport-https
  apt:
    name: apt-transport-https

# For handling ssh repositories
- name: package openssh-client
  apt:
    name: openssh-client

# For solving problems apt-get not able to solve
- name: package aptitude
  apt:
    name: aptitude
