---
- name: repo remove old files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - '/var/cache/apt/'
    - '/var/lib/apt/lists/'
  tags: build-child

- name: repo remove /etc/apt/sources.list.d/ubuntu.sources
  file:
    path: /etc/apt/sources.list.d/ubuntu.sources
    state: absent
  tags: build-child

### Preferences (pins)
- name: repo ubuntu pins
  template:
    src: "etc/apt/preferences.d/{{ item }}.pref.j2"
    dest: "/etc/apt/preferences.d/{{ item }}.pref"
  with_items: "{{ apt_repos }}"

- name: repo ubuntu ppa pin
  template:
    src: "etc/apt/preferences.d/ppa.pref.j2"
    dest: "/etc/apt/preferences.d/ppa.pref"

### Repos
- name: repo ubuntu
  template:
    src: "etc/apt/sources.list.d/{{ item }}.list.j2"
    dest: "/etc/apt/sources.list.d/{{ item }}.list"
  with_items: "{{ apt_repos }}"

- name: repo key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: FED902047AF1397755144CF6B47BBF2062DDDB70
    keyring: /etc/apt/trusted.gpg.d/ppa-pv-safronov-backports.gpg

- meta: flush_handlers

### Clean-up /etc/apt/sources.list
- name: repo sources.list
  template:
    src: etc/apt/sources.list.j2
    dest: /etc/apt/sources.list

### Run apt-get update after all
# FIXME: First run must use straight 'apt-get update' because the default way
# breaks on code "import apt; apt = apt.Cache()" used by ansible with:
# E:The value 'xenial' is invalid for APT::Default-Release as such a release
# is not available in the sources
- name: repo update
  shell:
    cmd: apt-get update
  tags:
    - build-child
