# Remove load-module module-bluetooth-discover
# because it is initializing too early and add it after x11 starts
# https://askubuntu.com/questions/481951/bluetooth-headset-connects-but-not-showing-in-sound-settings
- name: config /etc/pulse/default.pa
  template:
    dest: "/etc/pulse/default.pa"
    src: "etc/pulse/default.pa.j2"
    mode: '0644'

- name: config /usr/bin/start-pulseaudio-x11
  template:
    dest: "/usr/bin/start-pulseaudio-x11"
    src: "usr/bin/start-pulseaudio-x11.j2"
    mode: '0755'
