- name: config noise cancellation
  copy:
    dest: /etc/pulse/default.pa.d/noise-cancellation.pa
    content: |
      ### Enable noise cancellation
      # source: https://askubuntu.com/questions/18958/realtime-noise-removal-with-pulseaudio
      load-module module-echo-cancel source_name=noechosource sink_name=noechosink
      set-default-source noechosource
      set-default-sink noechosink
