- name: package node
  command: snap install node --classic

- name: package nvm
  become: true
  become_user: "{{ item.user }}"
  shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
  args:
    creates: "{{ item.home }}/.nvm/nvm.sh"
  with_items: "{{ users.values() | list }}"

- name: package nvm node
  become: true
  become_user: "{{ item.user }}"
  shell: >
    . {{ item.home }}/.nvm/nvm.sh && nvm install node
  with_items: "{{ users.values() | list }}"
