- name: repo ppa-keepassxc pins
  template:
    src: etc/apt/preferences.d/ppa-keepassxc.pref.j2
    dest: /etc/apt/preferences.d/ppa-keepassxc.pref

- name: repo
  template:
    src: etc/apt/sources.list.d/ppa-keepassxc.list.j2
    dest: /etc/apt/sources.list.d/ppa-keepassxc.list
  notify:
    - apt-get update

- name: repo key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: D89C66D0E31FEA2874EBD20561922AB60068FCD6
    keyring: /etc/apt/trusted.gpg.d/ppa-keepassxc.gpg
  notify:
    - apt-get update

- meta: flush_handlers
