- name: package nvidia-container-toolkit
  package:
    name: nvidia-container-toolkit
  notify:
    - nvidia-ctk runtime configure
    - nvidia-ctk cdi generate
    - nvidia-ctk user runtime configure
    - docker restart
