- name: repo pins
  template:
    src: etc/apt/preferences.d/nvidia.pref.j2
    dest: /etc/apt/preferences.d/nvidia.pref
  when: ansible_distribution == "Ubuntu"

- name: repo
  template:
    src: etc/apt/sources.list.d/nvidia.list.j2
    dest: /etc/apt/sources.list.d/nvidia.list
  notify:
    - apt-get update
  when: ansible_distribution == "Ubuntu"

- name: repo dir keyrings
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  when: ansible_distribution == "Ubuntu"

- name: repo remove legacy key
  file:
    path: /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg
    state: absent
  when: ansible_distribution == "Ubuntu"

- name: repo key
  get_url:
    url: https://nvidia.github.io/libnvidia-container/gpgkey
    dest: /etc/apt/keyrings/nvidia-container-toolkit.asc
    mode: '0644'
  notify:
    - apt-get update
  when: ansible_distribution == "Ubuntu"

- meta: flush_handlers
  when: ansible_distribution == "Ubuntu"
