- name: package qemu-system
  apt:
    name: qemu-system

- name: package qemu-system-arm
  apt:
    name: qemu-system-arm

- name: package qemu-efi-aarch64
  apt:
    name: qemu-efi-aarch64

- name: package qemu-utils
  apt:
    name: qemu-utils

- name: package libvirt-daemon
  apt:
    name: libvirt-daemon

- name: package libvirt-daemon-system
  apt:
    name: libvirt-daemon-system

- name: package uvtool
  apt:
    name: uvtool
