# https://wiki.ubuntu.com/DashAsBinSh
# Too many bugs because of dash as /bin/sh
# So we have choosen to hardcode this workaround
- name: config sh-bash
  file:
    state: link
    src: /bin/bash
    dest: /bin/sh

# Log bash history to syslog
- name: config bash-history-log
  template:
    src: etc/profile.d/history.sh.j2
    dest: /etc/profile.d/history.sh
    mode: '0644'

# Files like /etc/profile.d/vte-2.91.sh are trying to reassign PROMPT_COMMAND
# Except this this file does basically nothing, so we don't need it
- name: config remove vte profile.d scripts
  file:
    path: "{{ item }}"
    state: absent
  with_fileglob: /etc/profile.d/vte*.sh

- name: config user sysctl config
  copy:
    content: |
      fs.inotify.max_user_instances=8192
      net.ipv4.ping_group_range=1000 10000
    dest: /etc/sysctl.d/99-user.conf
    owner: "root"

- name: install available drivers
  shell:
    cmd: DEBIAN_FRONTEND=noninteractive ubuntu-drivers install
  when: ansible_virtualization_type != 'docker'

# This is needed for nvidia drivers to be correctly compiled and modules to be
# generated
- name: install kernel headers for current kernel
  ansible.builtin.apt:
    name: linux-headers-{{ ansible_kernel }}
    state: present
  when: ansible_kernel is not search("microsoft-standard-WSL")
