- name: repo ppa-i2p pins
  template:
    src: etc/apt/preferences.d/ppa-i2p.pref.j2
    dest: /etc/apt/preferences.d/ppa-i2p.pref

- name: repo
  template:
    src: etc/apt/sources.list.d/ppa-i2p.list.j2
    dest: /etc/apt/sources.list.d/ppa-i2p.list
  notify:
    - apt-get update

- name: repo key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 474BC46576FAE76E97C1A1A1AB9660B9EB2CC88B
    keyring: /etc/apt/trusted.gpg.d/ppa-i2p.gpg
  notify:
    - apt-get update

- meta: flush_handlers
