dependencies:
  - { role: tlp }
  - { role: chromium-browser }
  - { role: mongodb }
  - { role: docker }
  - { role: ponysay }
  - { role: i3 }
  - { role: skype }
  - { role: pulseaudio }
  - { role: openvpn }
  - { role: discord }
