- name: repo pins
  template:
    src: etc/apt/preferences.d/tailscale.pref.j2
    dest: /etc/apt/preferences.d/tailscale.pref
  when: ansible_distribution == "Ubuntu"

- name: repo
  template:
    src: etc/apt/sources.list.d/tailscale.list.j2
    dest: /etc/apt/sources.list.d/tailscale.list
  notify:
    - apt-get update
  when: ansible_distribution == "Ubuntu"

- name: repo key
  apt_key:
    id: 458CA832957F5868
    keyring: /usr/share/keyrings/tailscale-archive-keyring.gpg
    url: https://pkgs.tailscale.com/stable/ubuntu/jammy.noarmor.gpg
    state: present
  notify:
    - apt-get update
  when: ansible_distribution == "Ubuntu"

- meta: flush_handlers
  when: ansible_distribution == "Ubuntu"
