- name: repo pins
  template:
    src: etc/apt/preferences.d/tailscale.pref.j2
    dest: /etc/apt/preferences.d/tailscale.pref
  when: ansible_distribution == "Ubuntu"

- name: repo
  template:
    src: etc/apt/sources.list.d/tailscale.list.j2
    dest: /etc/apt/sources.list.d/tailscale.list
  notify:
    - apt-get update
  when: ansible_distribution == "Ubuntu"

- name: repo dir keyrings
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  when: ansible_distribution == "Ubuntu"

- name: repo remove legacy key
  file:
    path: /usr/share/keyrings/tailscale-archive-keyring.gpg
    state: absent
  when: ansible_distribution == "Ubuntu"

- name: repo key
  get_url:
    url: https://pkgs.tailscale.com/stable/ubuntu/jammy.asc
    dest: /etc/apt/keyrings/tailscale.asc
    mode: '0644'
  notify:
    - apt-get update
  when: ansible_distribution == "Ubuntu"

- meta: flush_handlers
  when: ansible_distribution == "Ubuntu"
