- name: packages
  apt:
    name: "{{ item }}"
  with_items:
    - i3
    - i3-wm
    - i3lock
    - i3status
    - libanyevent-i3-perl

- name: packages screenshot app
  apt:
    name: shutter

- name: package xss-lock
  apt:
    name: xss-lock

- name: package xautolock
  apt:
    name: xautolock

- name: packages remove screensavers
  apt:
    name: "{{ item }}"
    state: absent
  with_items:
    - gnome-screensaver
    - xscreensaver
