- name: packages
  apt:
    name: "{{ item }}"
  with_items:
    - i3
    - i3-wm
    - i3lock
    - i3status
    - libanyevent-i3-perl

- name: package xss-lock
  apt:
    name: xss-lock

- name: package xautolock
  apt:
    name: xautolock

- name: packages remove screensavers
  apt:
    name: "{{ item }}"
    state: absent
  with_items:
    - gnome-screensaver
    - xscreensaver

- name: package volumeicon-alsa
  apt:
    name: volumeicon-alsa

- name: package xdotool
  apt:
    name: xdotool

- name: package flameshot
  apt:
    name: flameshot

- name: package fcitx5
  package:
    name: fcitx5

- name: package fcitx5-table-translit-ua
  package:
    name: fcitx5-table-translit-ua
