---
- name: template smartctl_exporter.service
  become: true
  template:
    src: smartctl_exporter.service.j2
    dest: /etc/systemd/system/smartctl_exporter.service
  notify: restart smartctl_exporter

- name: service smartctl_exporter
  become: true
  systemd:
    name: smartctl_exporter
    enabled: true
    state: started
    daemon_reload: true