- name: repo key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 2A518C819BE37D2C2031944D1C52189C923F6CA9
  notify:
    - apt-get update

- name: repo ppa-ethereum pins
  template:
    src: etc/apt/preferences.d/ppa-ethereum.pref.j2
    dest: /etc/apt/preferences.d/ppa-ethereum.pref

- name: repo
  template:
    src: etc/apt/sources.list.d/ppa-ethereum.list.j2
    dest: /etc/apt/sources.list.d/ppa-ethereum.list
  notify:
    - apt-get update

- meta: flush_handlers
