---
- name: repo key
  apt_key:
    id: 798AEC654E5C15428C8E42EEAA16FCBCA621E701
    url: https://apt.releases.hashicorp.com/gpg
    keyring: /etc/apt/trusted.gpg.d/hashicorp.gpg
    state: present

- name: repo sources
  template:
    src: etc/apt/sources.list.d/hashicorp.list.j2
    dest: /etc/apt/sources.list.d/hashicorp.list
  notify:
    - apt-get update

- name: repo pin
  template:
    src: etc/apt/preferences.d/hashicorp.pref.j2
    dest: /etc/apt/preferences.d/hashicorp.pref
  notify:
    - apt-get update

- meta: flush_handlers
