- name: config nix bwrap fix
  copy:
    content: |
      abi <abi/4.0>,
      include <tunables/global>

      profile bwrap /nix/store/*/bin/bwrap flags=(unconfined) {
        userns,

        # Site-specific additions and overrides. See local/README for details.
        include if exists <local/bwrap>
      }

    dest: /etc/apparmor.d/bwrap
    owner: "root"
    mode: 0666
  # doesn't work on ubuntu 22.04 because abi/4.0 is not supported
  when:
    - ansible_facts['os_family'] == "Debian"
    - ansible_facts['distribution'] == "Ubuntu"
    - ansible_facts['distribution_version'] != "22.04"
