- name: config nix bwrap fix
  copy:
    content: |
      abi <abi/4.0>,
      include <tunables/global>

      profile bwrap /nix/store/*/bin/bwrap flags=(unconfined) {
        userns,

        # Site-specific additions and overrides. See local/README for details.
        include if exists <local/bwrap>
      }

    dest: /etc/apparmor.d/bwrap
    owner: "root"
    mode: 0666
