---
- name: template node_exporter.service
  become: true
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
  notify: restart node_exporter

- name: service node_exporter
  become: true
  systemd:
    name: node_exporter
    enabled: true
    state: started
    daemon_reload: true
  ignore_errors: "{{ ansible_virtualization_type == 'docker' }}"
