---
- name: service lvm-raid-check.timer
  become: true
  systemd:
    name: lvm-raid-check.timer
    enabled: true
    state: started
    daemon_reload: true
  ignore_errors: "{{ ansible_virtualization_type == 'docker' }}"
