dependencies:
  - { role: docker }
  - { role: libvirtd, when: ansible_virtualization_type != 'docker' }
  - { role: et }
  - { role: nvim }
  - { role: node_exporter }
  - { role: smartctl_exporter }
