- name: repo ppa-obs-studio pins
  template:
    src: etc/apt/preferences.d/ppa-obs-studio.pref.j2
    dest: /etc/apt/preferences.d/ppa-obs-studio.pref

- name: repo
  template:
    src: etc/apt/sources.list.d/ppa-obs-studio.list.j2
    dest: /etc/apt/sources.list.d/ppa-obs-studio.list
  notify:
    - apt-get update

- name: repo key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: BC7345F522079769F5BBE987EFC71127F425E228
  notify:
    - apt-get update

- meta: flush_handlers
