- name: repo ppa-ponysay pins
  template:
    src: etc/apt/preferences.d/ppa-ponysay.pref.j2
    dest: /etc/apt/preferences.d/ppa-ponysay.pref

- name: repo
  template:
    src: etc/apt/sources.list.d/ppa-ponysay.list.j2
    dest: /etc/apt/sources.list.d/ppa-ponysay.list
  notify:
    - apt-get update

- name: repo key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: FED902047AF1397755144CF6B47BBF2062DDDB70
  notify:
    - apt-get update

- meta: flush_handlers
