- name: repo ppa-ponysay pins
  template:
    src: etc/apt/preferences.d/ppa-ponysay.pref.j2
    dest: /etc/apt/preferences.d/ppa-ponysay.pref
  when: ansible_distribution == "Ubuntu"

- name: repo
  template:
    src: etc/apt/sources.list.d/ppa-ponysay.list.j2
    dest: /etc/apt/sources.list.d/ppa-ponysay.list
  notify:
    - apt-get update
  when: ansible_distribution == "Ubuntu"

- name: repo key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: FED902047AF1397755144CF6B47BBF2062DDDB70
    keyring: /etc/apt/trusted.gpg.d/ppa-ponysay.gpg
  notify:
    - apt-get update
  when: ansible_distribution == "Ubuntu"

- meta: flush_handlers
  when: ansible_distribution == "Ubuntu"
