---
- name: service power-profiles-daemon
  service:
    name: power-profiles-daemon
    enabled: no
    state: stopped
  # only needed before ubuntu noble, replaced by time-daemon after
  when:
    - ansible_facts['os_family'] == "Debian"
    - ansible_facts['distribution'] == "Ubuntu"
    - ansible_facts['distribution_version'] == "22.04"

- name: service tlp
  service:
    name: tlp
    enabled: yes
    state: started
