---
- name: service ondemand tlp
  service:
    name: ondemand
    enabled: no
    state: stopped
  # FIXME: missing since Ubuntu jammy
  ignore_errors: yes

- name: service power-profiles-daemon
  service:
    name: power-profiles-daemon
    enabled: no
    state: stopped

- name: service tlp
  service:
    name: tlp
    enabled: yes
    state: started
