---
- name: package virtualbox
  apt:
    name: "{{ item }}"
  with_items:
    - virtualbox

# Might need to run apt-get dist-upgrade to install the latest kernel
- name: package check if virtualbox
  shell: lspci | grep VirtualBox
  register: runningvirtualbox
  ignore_errors: True

- name: package virtualbox-guest-additions
  apt:
    name: "{{ item }}"
  with_items:
    - virtualbox-guest-utils
    - virtualbox-guest-dkms
    - virtualbox-guest-x11
  when: runningvirtualbox.rc == 0
