- name: repo tor key
  apt_key:
    url: https://deb.torproject.org/torproject.org/A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89.asc
  notify:
    - apt-get update

- name: repo torbrowser-launcher key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 7EF33F027E9E4869F46F77E34E72F77D7D158F33
  notify:
    - apt-get update

- name: repo torproject pins
  template:
    src: etc/apt/preferences.d/torproject.pref.j2
    dest: /etc/apt/preferences.d/torproject.pref

- name: repo torproject
  template:
    src: etc/apt/sources.list.d/torproject.list.j2
    dest: /etc/apt/sources.list.d/torproject.list
  notify:
    - apt-get update

- name: repo ppa-torbrowser-launcher pins
  template:
    src: etc/apt/preferences.d/ppa-torbrowser-launcher.pref.j2
    dest: /etc/apt/preferences.d/ppa-torbrowser-launcher.pref

- name: repo torbrowser-launcher
  template:
    src: etc/apt/sources.list.d/ppa-torbrowser-launcher.list.j2
    dest: /etc/apt/sources.list.d/ppa-torbrowser-launcher.list
  notify:
    - apt-get update

- name: repo keyring package
  apt:
    name: deb.torproject.org-keyring
    allow_unauthenticated: yes
    state: latest
    update_cache: yes
  notify:
    - apt-get update

- meta: flush_handlers
