---
- name: config apc-ups udev rule
  become: true
  template:
    src: etc/udev/rules.d/99-apc-ups.rules.j2
    dest: /etc/udev/rules.d/99-apc-ups.rules
    owner: root
    group: root
    mode: '0644'
  notify:
    - reload udev
    - trigger udev
