- name: config lightdm key repeat
  copy:
    dest: /etc/lightdm/lightdm.conf.d/00-setkbrate.conf
    content: |
      [Seat:*]
      xserver-command=X -ardelay 250 -arinterval 15

- name: config set default
  copy:
    dest: /etc/X11/default-display-manager
    content: |
      /usr/sbin/lightdm

- name: config set default service
  file:
    src: /lib/systemd/system/lightdm.service
    dest: /etc/systemd/system/display-manager.service
    state: link
