- name: repo apt key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 1F3045A5DF7587C3
    keyring: /etc/apt/trusted.gpg.d/ppa-obs-studio.gpg
  notify:
    - apt-get update

- name: repo sources
  template:
    src: etc/apt/sources.list.d/skype.list.j2
    dest: /etc/apt/sources.list.d/skype-stable.list
  notify:
    - apt-get update

- name: repo pin
  template:
    src: etc/apt/preferences.d/skype.pref.j2
    dest: /etc/apt/preferences.d/skype.pref
  notify:
    - apt-get update

- meta: flush_handlers
