- name: key file
  get_url:
    url: https://cli.github.com/packages/githubcli-archive-keyring.gpg
    checksum: "sha256:a5eb97c717ec3438bb94d465554e3560f8732403c28870780f779b8ab89975ea"
    dest: /usr/share/keyrings/githubcli-archive-keyring.gpg
    mode: '0444'

- name: repo sources
  template:
    src: etc/apt/sources.list.d/github-cli.list.j2
    dest: /etc/apt/sources.list.d/github-cli.list
  notify:
    - apt-get update

- name: repo pin
  template:
    src: etc/apt/preferences.d/github-cli.pref.j2
    dest: /etc/apt/preferences.d/github-cli.pref
  notify:
    - apt-get update

- meta: flush_handlers
