- name: config systemd dir
  file:
    path: /etc/systemd/system/docker.service.d/
    state: directory

- name: config systemd custom docker opts
  template:
    src: etc/systemd/system/docker.service.d/custom-docker-opts.conf
    dest: /etc/systemd/system/docker.service.d/custom-docker-opts.conf
  notify:
    - docker restart

- name: config default config
  template:
    src: etc/docker/daemon.json.j2
    dest: /etc/docker/daemon.json
  notify:
    - docker restart

- name: config user dir
  file:
    path: "{{ item.home }}/.config/docker-user/"
    state: directory
    owner: "{{ item.user }}"
    mode: '0700'
  with_items: "{{ users.values() | list }}"

- name: config user mounts
  copy:
    content: "{{ docker_config_run_args }}"
    dest: "{{ item.home }}/.config/docker-user/run-args"
    owner: "{{ item.user }}"
    mode: '0600'
  with_items: "{{ users.values() | list }}"

- name: config docker cleanup service
  template:
    src: etc/systemd/system/docker-cleanup.service
    dest: /etc/systemd/system/docker-cleanup.service

- name: config docker cleanup timer
  template:
    src: etc/systemd/system/docker-cleanup.timer
    dest: /etc/systemd/system/docker-cleanup.timer

- name: config podman cleanup service
  template:
    src: etc/systemd/system/podman-cleanup.service
    dest: /etc/systemd/system/podman-cleanup.service

- name: config podman cleanup timer
  template:
    src: etc/systemd/system/podman-cleanup.timer
    dest: /etc/systemd/system/podman-cleanup.timer

- name: config nvidia cdi generate service
  template:
    src: etc/systemd/system/nvidia-cdi-generate.service
    dest: /etc/systemd/system/nvidia-cdi-generate.service
  when: nvidia | default(false)

- name: config nvidia-ctk containerd service
  template:
    src: etc/systemd/system/nvidia-ctk-containerd-config.service
    dest: /etc/systemd/system/nvidia-ctk-containerd-config.service
  when: nvidia | default(false)

- name: config nvidia-ctk crio service
  template:
    src: etc/systemd/system/nvidia-ctk-crio-config.service
    dest: /etc/systemd/system/nvidia-ctk-crio-config.service
  when: nvidia | default(false)

- name: config nvidia-ctk docker user service
  become: true
  become_user: "{{ item.user }}"
  template:
    src: etc/systemd/user/nvidia-ctk-docker-config.service
    dest: "/home/{{ item.user }}/.config/systemd/user/nvidia-ctk-docker-config.service"
    mode: '0644'
  loop: "{{ users.values() }}"
  when: nvidia | default(false)
