- name: package docker
  apt:
    name: "{{ item }}"
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin

- name: package podman
  apt:
    name: "{{ item }}"
  with_items:
    - podman
    - podman-compose
    - crun
  when: ansible_distribution != 'Ubuntu' or ansible_distribution_version != '22.04'

- name: package remove unused
  apt:
    name: "{{ item }}"
    state: absent
  with_items:
    - docker.io
    - docker-compose
    - docker-compose-v2
    - docker-doc
