- name: repo key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /etc/apt/trusted.gpg.d/docker.gpg

- name: repo
  template:
    src: etc/apt/sources.list.d/docker-ce.list
    dest: /etc/apt/sources.list.d/docker-ce.list
  notify:
    - apt-get update

- name: repo
  template:
    src: etc/apt/preferences.d/docker-ce.pref.j2
    dest: /etc/apt/preferences.d/docker-ce.pref
  notify:
    - apt-get update

- meta: flush_handlers
