---
- name: package sway
  package:
    name: sway

- name: package sway-backgrounds
  package:
    name: sway-backgrounds

- name: package swaybg
  package:
    name: swaybg

- name: package swayidle
  package:
    name: swayidle

- name: package swaylock
  package:
    name: swaylock

- name: package light
  package:
    name: light

- name: package grim
  package:
    name: grim

- name: package slurp
  package:
    name: slurp

- name: package waybar
  package:
    name: waybar

- name: package wev
  package:
    name: wev

- name: package wtype
  package:
    name: wtype

- name: package libappindicator1
  package:
    name: libappindicator1
  # removed since ubuntu noble
  when:
    - ansible_facts['os_family'] == "Debian"
    - ansible_facts['distribution'] == "Ubuntu"
    - ansible_facts['distribution_version'] == "22.04"

- name: package qtwayland5
  package:
    name: qtwayland5

- name: package qt5-style-plugins
  package:
    name: qt5-style-plugins

- name: package adwaita-qt
  package:
    name: adwaita-qt

- name: package wdisplays
  package:
    name: wdisplays

- name: package fcitx
  package:
    name: fcitx

- name: package fcitx-table-translit-ua
  package:
    name: fcitx-table-translit-ua

- name: package policykit-1-gnome
  package:
    name: policykit-1-gnome

- name: package polkit-kde-agent-1
  package:
    name: polkit-kde-agent-1

- name: package xdg-desktop-portal-wlr
  package:
    name: xdg-desktop-portal-wlr
