---
- name: package sway
  package:
    name: sway

- name: package sway-backgrounds
  package:
    name: sway-backgrounds

- name: package swaybg
  package:
    name: swaybg

- name: package swayidle
  package:
    name: swayidle

- name: package swaylock
  package:
    name: swaylock

- name: package light
  package:
    name: light

- name: package grim
  package:
    name: grim

- name: package slurp
  package:
    name: slurp

- name: package waybar
  package:
    name: waybar

- name: package wev
  package:
    name: wev

- name: package wtype
  package:
    name: wtype

- name: package libappindicator1
  package:
    name: libappindicator1

- name: package qtwayland5
  package:
    name: qtwayland5

- name: package qt5-style-plugins
  package:
    name: qt5-style-plugins

- name: package adwaita-qt
  package:
    name: adwaita-qt

- name: package wdisplays
  package:
    name: wdisplays
