- name: config virtualenv
  become: true
  become_user: "{{ item.user }}"
  shell: >
    virtualenv -p python3 {{ item.home  }}/venv/neovim
  with_items: "{{ users.values() | list }}"

- name: config virtualenv packages
  become: true
  become_user: "{{ item.user }}"
  shell: >
    . ~/venv/neovim/bin/activate && pip install neovim jedi
  with_items: "{{ users.values() | list }}"
