default_groups:
  - audio
  - cdrom
  - dip
  - plugdev
  - lpadmin

default_admin_groups:
  - sudo

# users:
#   user:
#     user: user
#     uid: 1111
#     home: '/home/user'
#     comment: 'test user'
#     admin: false
#     password: '$6$hUiR3A81$J.Zt0Sazk8HJkSbcxRKGeAIsqv5ImFgiQl2tEU.XmYaOoUKtNYqITUyA.J5UIHmB0eCkrvx6p0RhM293mBYLx.'
#     gpg_keys: []
#   admin:
#     user: admin
#     uid: 2222
#     home: '/home/admin'
#     comment: 'test admin'
#     admin: true
#     password: '$6$D0JC.bteG2$V7UbECG.4Bzo5pf0FToc1yiQp9U3yCv38OMm1gtq/GsXPARbCHHEyO20tQSfeZ3eBcxlUfwlhlFX.oH5ou5.m0'
#     gpg_keys: []
