default_groups:
  - audio
  - cdrom
  - dip
  - plugdev
  - lpadmin

default_admin_groups:
  - sudo

# users:
#   user:
#     user: user
#     uid: 1111
#     home: '/home/user'
#     comment: ''
#     admin: false
#     password: ''
#     gpg_keys: []
