dependencies:
  - { role: user, when: ansible_distribution == "Ubuntu" }
  - { role: pkgmanager }
  - { role: tzdata }
  - { role: systemd}
  - { role: ntp, when: ansible_distribution == "Ubuntu" }
  - { role: gpg, when: ansible_distribution == "Ubuntu" }
  - { role: iptables, when: ansible_distribution == "Ubuntu" }
  - { role: locales, when: ansible_distribution == "Ubuntu" }
