name: vagrant-up

on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  vagrant-set-up:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
      # - name: Setup upterm session
      #   uses: lhotari/action-upterm@v1
