name: vagrant-up

on: [push]

jobs:
  vagrant-set-up:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: add repo
        run: echo "deb [arch=amd64] https://apt.releases.hashicorp.com jammy main" | sudo tee /etc/apt/sources.list.d/hashicorp.list

      - name: add key
        run: wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/hashicorp.gpg

      - name: apt update
        run: sudo apt-get update

      - name: install packages
        run: sudo apt install -y virtualbox virtualbox-guest-utils virtualbox-guest-dkms virtualbox-guest-x11 vagrant git

      - name: init submodules
        run: git submodule update --init --recursive

      - name: Show Vagrant version
        run: vagrant --version

  vagrant-user:
    runs-on: self-hosted

    needs: vagrant-set-up
    steps:
      - name: Run vagrant user.yml
        run: vagrant --os=ubuntu/jammy64 --local --playbook=user.yml --headless up

      - name: Destroy vagrant user.yml
        run: timeout -k 60 -s 9 60 vagrant destroy -f || true
        if: always()

  vagrant-common-desktop:
    runs-on: self-hosted

    needs: vagrant-set-up
    steps:
      - name: Run vagrant common-desktop.yml
        run: vagrant --os=ubuntu/jammy64 --local --headless up

      - name: Destroy vagrant common-desktop.yml
        run: timeout -k 60 -s 9 60 vagrant destroy -f || true
        if: always()

  vagrant-common-minimal-desktop:
    runs-on: self-hosted

    needs: vagrant-set-up
    steps:
      - name: Run vagrant common-minimal-desktop.yml
        run: vagrant --os=ubuntu/jammy64 --local --playbook=common-minimal-desktop.yml --headless up

      - name: Destroy vagrant common-minimal-desktop.yml
        run: timeout -k 60 -s 9 60 vagrant destroy -f || true
        if: always()

  vagrant-user-2404:
    runs-on: self-hosted

    needs: vagrant-set-up
    steps:
      - name: Run vagrant user.yml
        run: vagrant --os=bento/ubuntu-24.04 --local --playbook=user.yml --headless up

      - name: Destroy vagrant user.yml
        run: timeout -k 60 -s 9 60 vagrant destroy -f || true
        if: always()

  vagrant-common-desktop-2404:
    runs-on: self-hosted

    needs: vagrant-set-up
    steps:
      - name: Run vagrant common-desktop.yml
        run: vagrant --os=bento/ubuntu-24.04 --local --headless up

      - name: Destroy vagrant common-desktop.yml
        run: timeout -k 60 -s 9 60 vagrant destroy -f || true
        if: always()
