name: vagrant-up

on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  vagrant-set-up:
    runs-on: macos-latest-large

    steps:
      - uses: actions/checkout@v2
      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
        with:
          # Optional: limit access to specific SSH keys
          limit-access-to-actor: true
          # Optional: limit access to specific users
          limit-access-to-users: fspv
