name: vagrant-up

on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  vagrant-set-up:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: add repo
        run: echo "deb [arch=amd64] https://apt.releases.hashicorp.com jammy main" | sudo tee /etc/apt/sources.list.d/hashicorp.list

      - name: add key
        run: wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/hashicorp.gpg

      - name: apt update
        run: sudo apt-get update

      - name: install packages
        run: sudo apt install -y virtualbox virtualbox-guest-utils virtualbox-guest-x11 vagrant git qemu-system libvirt-dev

      - name: init submodules
        run: git submodule update --init --recursive

      - name: Show Vagrant version
        run: VAGRANT_LOG=debug vagrant --version

      - name: Install libvirt plugin
        run: VAGRANT_LOG=debug vagrant plugin install vagrant-libvirt

  uvt-user-2404:
    runs-on: self-hosted
    env:
      SSH_OPTS: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"

    steps:
      - uses: actions/checkout@v2

      - name: init submodules
        run: git submodule update --init --recursive

      - name: Destroy existing VM if exists
        run: sudo uvt-kvm destroy uvt-user-2404 || true
        if: always()

      - name: Install uvtool
        run: sudo apt install -y uvtool

      - name: Sync Ubuntu Noble image
        run: sudo uvt-simplestreams-libvirt -v sync release=noble arch=amd64

      - name: Create SSH key if not exists
        run: sudo test -f /root/.ssh/id_rsa || sudo ssh-keygen -t rsa -b 2048 -f /root/.ssh/id_rsa -N ""

      - name: Create VM
        run: sudo uvt-kvm create uvt-user-2404 release=noble --memory 4096

      - name: Wait for VM
        run: sudo uvt-kvm wait uvt-user-2404

      - name: Get VM IP
        id: get_ip
        run: echo "IP=$(sudo uvt-kvm ip uvt-user-2404)" >> $GITHUB_OUTPUT

      - name: Sync files to VM
        run: sudo rsync -avz --delete -e "ssh $SSH_OPTS" ./ ubuntu@${{ steps.get_ip.outputs.IP }}:/home/ubuntu/ansible-playbooks/

      - name: Clean manual directory
        run: sudo uvt-kvm ssh uvt-user-2404 -- "cd ansible-playbooks && rm -rf manual"

      - name: Create manual directory
        run: sudo uvt-kvm ssh uvt-user-2404 -- "cd ansible-playbooks && mkdir manual"

      - name: Generate common.yml
        run: sudo uvt-kvm ssh uvt-user-2404 -- "cd ansible-playbooks && sed 's/# //g' roles/user/defaults/main.yml > manual/common.yml"

      - name: Run bootstrap script
        run: sudo uvt-kvm ssh uvt-user-2404 -- "cd ansible-playbooks && ./bootstrap.sh user.yml LOCAL"

      - name: Update package lists
        run: sudo uvt-kvm ssh uvt-user-2404 -- "sudo apt-get update"

      - name: Upgrade packages
        run: sudo uvt-kvm ssh uvt-user-2404 -- "sudo apt-get -y upgrade"

      - name: Distribution upgrade
        run: sudo uvt-kvm ssh uvt-user-2404 -- "sudo apt-get -y dist-upgrade"

      - name: Final upgrade
        run: sudo uvt-kvm ssh uvt-user-2404 -- "sudo apt-get -y upgrade"

      - name: Autoremove packages
        run: sudo uvt-kvm ssh uvt-user-2404 -- "sudo apt-get -y autoremove"

      - name: Destroy VM
        run: sudo uvt-kvm destroy uvt-user-2404
        if: always()

  uvt-common-desktop-2404:
    runs-on: self-hosted
    env:
      SSH_OPTS: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"

    steps:
      - uses: actions/checkout@v2

      - name: init submodules
        run: git submodule update --init --recursive

      - name: Destroy existing VM if exists
        run: sudo uvt-kvm destroy uvt-common-desktop-2404 || true
        if: always()

      - name: Install uvtool
        run: sudo apt install -y uvtool

      - name: Sync Ubuntu Noble image
        run: sudo uvt-simplestreams-libvirt -v sync release=noble arch=amd64

      - name: Create SSH key if not exists
        run: sudo test -f /root/.ssh/id_rsa || sudo ssh-keygen -t rsa -b 2048 -f /root/.ssh/id_rsa -N ""

      - name: Create VM
        run: sudo uvt-kvm create uvt-common-desktop-2404 release=noble --memory 4096

      - name: Wait for VM
        run: sudo uvt-kvm wait uvt-common-desktop-2404

      - name: Get VM IP
        id: get_ip
        run: echo "IP=$(sudo uvt-kvm ip uvt-common-desktop-2404)" >> $GITHUB_OUTPUT

      - name: Sync files to VM
        run: sudo rsync -avz --delete -e "ssh $SSH_OPTS" ./ ubuntu@${{ steps.get_ip.outputs.IP }}:/home/ubuntu/ansible-playbooks/

      - name: Clean manual directory
        run: sudo uvt-kvm ssh uvt-common-desktop-2404 -- "cd ansible-playbooks && rm -rf manual"

      - name: Create manual directory
        run: sudo uvt-kvm ssh uvt-common-desktop-2404 -- "cd ansible-playbooks && mkdir manual"

      - name: Generate common.yml
        run: sudo uvt-kvm ssh uvt-common-desktop-2404 -- "cd ansible-playbooks && sed 's/# //g' roles/user/defaults/main.yml > manual/common.yml"

      - name: Run bootstrap script
        run: sudo uvt-kvm ssh uvt-common-desktop-2404 -- "cd ansible-playbooks && ./bootstrap.sh common-desktop.yml LOCAL"

      - name: Update package lists
        run: sudo uvt-kvm ssh uvt-common-desktop-2404 -- "sudo apt-get update"

      - name: Upgrade packages
        run: sudo uvt-kvm ssh uvt-common-desktop-2404 -- "sudo apt-get -y upgrade"

      - name: Distribution upgrade
        run: sudo uvt-kvm ssh uvt-common-desktop-2404 -- "sudo apt-get -y dist-upgrade"

      - name: Final upgrade
        run: sudo uvt-kvm ssh uvt-common-desktop-2404 -- "sudo apt-get -y upgrade"

      - name: Autoremove packages
        run: sudo uvt-kvm ssh uvt-common-desktop-2404 -- "sudo apt-get -y autoremove"

      - name: Destroy VM
        run: sudo uvt-kvm destroy uvt-common-desktop-2404
        if: always()

  uvt-common-devserver-2404:
    runs-on: self-hosted
    env:
      SSH_OPTS: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"

    steps:
      - uses: actions/checkout@v2

      - name: init submodules
        run: git submodule update --init --recursive

      - name: Destroy existing VM if exists
        run: sudo uvt-kvm destroy uvt-common-devserver-2404 || true
        if: always()

      - name: Install uvtool
        run: sudo apt install -y uvtool

      - name: Sync Ubuntu Noble image
        run: sudo uvt-simplestreams-libvirt -v sync release=noble arch=amd64

      - name: Create SSH key if not exists
        run: sudo test -f /root/.ssh/id_rsa || sudo ssh-keygen -t rsa -b 2048 -f /root/.ssh/id_rsa -N ""

      - name: Create VM
        run: sudo uvt-kvm create uvt-common-devserver-2404 release=noble --memory 4096

      - name: Wait for VM
        run: sudo uvt-kvm wait uvt-common-devserver-2404

      - name: Get VM IP
        id: get_ip
        run: echo "IP=$(sudo uvt-kvm ip uvt-common-devserver-2404)" >> $GITHUB_OUTPUT

      - name: Sync files to VM
        run: sudo rsync -avz --delete -e "ssh $SSH_OPTS" ./ ubuntu@${{ steps.get_ip.outputs.IP }}:/home/ubuntu/ansible-playbooks/

      - name: Clean manual directory
        run: sudo uvt-kvm ssh uvt-common-devserver-2404 -- "cd ansible-playbooks && rm -rf manual"

      - name: Create manual directory
        run: sudo uvt-kvm ssh uvt-common-devserver-2404 -- "cd ansible-playbooks && mkdir manual"

      - name: Generate common.yml
        run: sudo uvt-kvm ssh uvt-common-devserver-2404 -- "cd ansible-playbooks && sed 's/# //g' roles/user/defaults/main.yml > manual/common.yml"

      - name: Run bootstrap script
        run: sudo uvt-kvm ssh uvt-common-devserver-2404 -- "cd ansible-playbooks && ./bootstrap.sh common-devserver.yml LOCAL"

      - name: Update package lists
        run: sudo uvt-kvm ssh uvt-common-devserver-2404 -- "sudo apt-get update"

      - name: Upgrade packages
        run: sudo uvt-kvm ssh uvt-common-devserver-2404 -- "sudo apt-get -y upgrade"

      - name: Distribution upgrade
        run: sudo uvt-kvm ssh uvt-common-devserver-2404 -- "sudo apt-get -y dist-upgrade"

      - name: Final upgrade
        run: sudo uvt-kvm ssh uvt-common-devserver-2404 -- "sudo apt-get -y upgrade"

      - name: Autoremove packages
        run: sudo uvt-kvm ssh uvt-common-devserver-2404 -- "sudo apt-get -y autoremove"

      - name: Destroy VM
        run: sudo uvt-kvm destroy uvt-common-devserver-2404
        if: always()

  vagrant-common-devserver-2404-arm64:
    runs-on: self-hosted

    needs: vagrant-set-up
    steps:
      - name: Run libvirt common-devserver.yml
        run: VAGRANT_DEFAULT_PROVIDER=libvirt VAGRANT_LOG=debug ./bin/retry.sh vagrant --destroy-on-error --os=cloud-image/ubuntu-24.04 --local --playbook=common-devserver.yml --headless --architecture=arm64 up

      - name: Destroy libvirt common-devserver.yml
        run: VAGRANT_DEFAULT_PROVIDER=libvirt timeout -k 60 -s 9 60 vagrant destroy -f || true
        if: always()

      - name: Destroy all libvirt machines
        run: virsh list --all | awk -F' ' '/.*ansible-playbooks.*/ {print $2}' | xargs -I {} virsh destroy {}
        if: always()